### ISSUE TITLE
npm install error: multihashing.target.mk:195: recipe for target 'Release/obj.target/multihashing/m7.o' failed

### ISSUE THREAD

**Issue by peipeitu** [ROZ-MOFUMOFU-ME/node-multi-hashing-yescrypt-0.5#7]
Error when running npm install.
And here are the details:
```
../m7.c:1:10: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
          ^~~~~~~
compilation terminated.
multihashing.target.mk:195: recipe for target 'Release/obj.target/multihashing/m7.o' failed
make: *** [Release/obj.target/multihashing/m7.o] Error 1
make: Leaving directory '/root/stratums/dmhc/current/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-96-generic
gyp ERR! command "/root/node/bin/node" "/root/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/stratums/dmhc/current/node_modules/multi-hashing
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm verb lifecycle multi-hashing@0.0.9~install: unsafe-perm in lifecycle true
npm verb lifecycle multi-hashing@0.0.9~install: PATH: /root/node/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/stratums/dmhc/current/node_modules/multi-hashing/node_modules/.bin:/root/stratums/dmhc/current/node_modules/.bin:/root/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

**Comment by ROZ-MOFUMOFU-ME** [comment]
If you using Ubuntu, you might want to do this
`sudo apt-get install libgmp-dev`

**Comment by peipeitu** [comment]
Thanks! It worked.
